version: "3.3"

services:
  codeserver:
    image: lscr.io/linuxserver/code-server:latest
    volumes:
      - ${HOST_FOLDER_PATH}:/config
    tty: true
    stdin_open: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      #- PASSWORD=password #optional
      #- HASHED_PASSWORD= #optional
      #- SUDO_PASSWORD=password #optional
      #- SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=${CODESERVER_DOMAIN}
      - DEFAULT_WORKSPACE=/config/workspace #optional
    networks:
      - traefik-public
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - ${NODE_PLACEMENT}
      labels:
        traefik.enable: "true"
        traefik.http.routers.codeserver.rule: HostRegexp(`${CODESERVER_DOMAIN}`, `{subdomain:[a-z0-9]+}.${CODESERVER_DOMAIN}`)
        traefik.http.routers.codeserver.entrypoints: websecure
        traefik.http.routers.codeserver.tls.certresolver: wildcard
        traefik.http.routers.codeserver.tls.domains[0].main: "${CODESERVER_DOMAIN}"
        traefik.http.routers.codeserver.tls.domains[0].sans: "*.${CODESERVER_DOMAIN}"
        traefik.http.routers.codeserver.service: svc_codeserver
        traefik.http.services.svc_codeserver.loadbalancer.server.port: 8443

    
    

networks:
  traefik-public:
    external: true